<?php
/**
*implementacion de modulo
*/
function Banco_menu(){
$items['Banco']=array(
'title'=>'Indicador de Produccion de Petroleo',
'description'=>'Impresion de Indicador',
'page callback'=>'indicadores',
'type'=>MENU_NORMAL_ITEM,
'access callback'=>TRUE,
);
return $items;
}
function indicadores(){
$resultado=drupal_http_request("http://api.worldbank.org/es/countries/COL/indicators/EG.USE.CRNW.KT.OE?per_page=10&date=1990:2010");

//print "<pre>";

if ($resultado->code=200)
{
	$datos==$resultado->data;
	if(is_array($datos))
	{
	print "<img src='http://chart.apis.google.com/chart?cht=p3&chd=t:60,40&chs=250x100&chl=Hello|World'/>";
	}
}
//print "<img src='http://chart.apis.google.com/chart?cht=p3&chd=t:60,40&chs=250x100&chl=Hello|World'/>";

//return print_r($resultado);

$hola=simplexml_load_string($resultado->data);

$a=0;
	
foreach($hola->children("http://www.worldbank.org")->data as $dato){
	
	$indi=$dato->indicator;
	$pais=$dato->country;
	$fecha=$dato->date;
	$valor=$dato->value;

	//print $indi;
	//print "\t";
	//print $pais;
	//print "\t";
	//print $fecha;
	//print "\t";
	//print $valor;
	//print "\n";
	



if($a==0)
{
	$resultadofecha=$resultadofecha.$fecha;
        $resultadovalor=$resultadovalor.$valor;
	
}


if($a>0)
{
	$resultadofecha=$resultadofecha.'|'.$fecha;
        $resultadovalor=$resultadovalor.','.$valor;
}

$a=$a+1;

	

//return print_r($hola);


}
//print $resultadofecha;

//print $resultadovalor;

//print "<img src='http://chart.apis.google.com/chart?cht=p3&chco=0000FF&chd=t:$resultadovalor&chs=500x250&chl=$resultadofecha&chtt=Diagrama+Circular&chts=CC3366,30'/>";
$xx="<img src='http://chart.apis.google.com/chart?cht=p3&chco=0000FF&chd=t:$resultadovalor&chs=500x250&chl=$resultadofecha&chtt=Diagrama+Circular&chts=CC3366,30'/>"."<img src='http://chart.apis.google.com/chart?cht=bvs&chd=t:$resultadovalor&chs=600x400&chl=$resultadofecha&chco=990066|00A5C6|80C65A&chtt=Diagrama+de+Barras&chts=CC3366,30&chds=0,10000&chxt=x,y&chxr=0,0,10000|1,0,10000,500'/>";
//print "<img src='http://chart.apis.google.com/chart?cht=bvs&chd=t:$resultadovalor&chs=600x400&chl=$resultadofecha&chco=990066|00A5C6|80C65A&chtt=Diagrama+de+Barras&chts=CC3366,30&chds=0,10000&chxt=x,x,y,y&chx1=1:|Fecha|3:|Valor&chxp=1,50|3,50&chxr=0,0,10000|1,0,10000,500'/>";

return ($xx);
//print "</pre>";

//PHP es un lenguaje de programación interpretado, diseñado originalmente para la creación de páginas web dinámicas. Es usado principalmente en interpretación del lado del servidor (server-side scripting) pero actualmente puede ser utilizado desde una interfaz de línea de comandos o en la creación de otros tipos de programas incluyendo aplicaciones con interfaz gráfica usando las bibliotecas Qt o GTK+.





}